import type { Candidate } from './schema';

// Fake candidate DB stand-in. Owners reference the consultants in
// features/users/mock.ts so the pages feel relationally connected.
export const mockCandidates: Candidate[] = [
  {
    id: 'cand_01',
    name: 'Wei Lin Tan',
    email: 'weilin.tan@example.com',
    role: 'Senior Backend Engineer',
    currentCompany: 'Meridian Payments',
    location: 'Singapore',
    status: 'INTERVIEW',
    expectedSalary: 165000,
    noticePeriodDays: 30,
    owner: 'Daniel Wong',
    notes: 'Strong Go + distributed systems background.',
    createdAt: '2026-05-12T09:00:00Z',
    updatedAt: '2026-07-06T14:20:00Z',
  },
  {
    id: 'cand_02',
    name: 'Aisha Rahman',
    email: 'aisha.rahman@example.com',
    role: 'Product Manager',
    currentCompany: 'Northwind Logistics',
    location: 'Kuala Lumpur',
    status: 'SCREENING',
    expectedSalary: 140000,
    noticePeriodDays: 60,
    owner: 'Sofia Reyes',
    notes: null,
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-07-07T10:05:00Z',
  },
  {
    id: 'cand_03',
    name: 'James O’Connor',
    email: 'james.oconnor@example.com',
    role: 'Data Scientist',
    currentCompany: 'Cobalt Analytics',
    location: 'Singapore',
    status: 'OFFER',
    expectedSalary: 155000,
    noticePeriodDays: 30,
    owner: 'Leila Haddad',
    notes: 'Awaiting counter-offer decision.',
    createdAt: '2026-04-20T09:00:00Z',
    updatedAt: '2026-07-08T08:30:00Z',
  },
  {
    id: 'cand_04',
    name: 'Mei Ling Chua',
    email: 'meiling.chua@example.com',
    role: 'UX Designer',
    currentCompany: 'Lumen Studio',
    location: 'Singapore',
    status: 'APPLIED',
    expectedSalary: 98000,
    noticePeriodDays: 14,
    owner: 'Hannah Kim',
    notes: null,
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-02T09:00:00Z',
  },
  {
    id: 'cand_05',
    name: 'Ravi Menon',
    email: 'ravi.menon@example.com',
    role: 'DevOps Engineer',
    currentCompany: 'Meridian Payments',
    location: 'Bangalore',
    status: 'HIRED',
    expectedSalary: 120000,
    noticePeriodDays: 45,
    owner: 'Daniel Wong',
    notes: 'Placed at Northwind Logistics.',
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-06-28T16:00:00Z',
  },
  {
    id: 'cand_06',
    name: 'Sophie Laurent',
    email: 'sophie.laurent@example.com',
    role: 'Engineering Manager',
    currentCompany: 'Atlas Fintech',
    location: 'Singapore',
    status: 'INTERVIEW',
    expectedSalary: 210000,
    noticePeriodDays: 90,
    owner: 'Marcus Tan',
    notes: null,
    createdAt: '2026-05-28T09:00:00Z',
    updatedAt: '2026-07-05T11:45:00Z',
  },
  {
    id: 'cand_07',
    name: 'Kwame Boateng',
    email: 'kwame.boateng@example.com',
    role: 'Frontend Engineer',
    currentCompany: 'Lumen Studio',
    location: 'Remote',
    status: 'SCREENING',
    expectedSalary: 110000,
    noticePeriodDays: 30,
    owner: 'Grace Ofori',
    notes: 'React + TypeScript, strong portfolio.',
    createdAt: '2026-06-18T09:00:00Z',
    updatedAt: '2026-07-04T09:15:00Z',
  },
  {
    id: 'cand_08',
    name: 'Hiroshi Nakamura',
    email: 'hiroshi.nakamura@example.com',
    role: 'Solutions Architect',
    currentCompany: 'Cobalt Analytics',
    location: 'Tokyo',
    status: 'REJECTED',
    expectedSalary: 180000,
    noticePeriodDays: 60,
    owner: 'Yuki Sato',
    notes: 'Withdrew — accepted internal move.',
    createdAt: '2026-04-10T09:00:00Z',
    updatedAt: '2026-06-20T13:30:00Z',
  },
  {
    id: 'cand_09',
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    role: 'QA Lead',
    currentCompany: 'Northwind Logistics',
    location: 'Singapore',
    status: 'APPLIED',
    expectedSalary: 115000,
    noticePeriodDays: 30,
    owner: 'Isabella Rossi',
    notes: null,
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'cand_10',
    name: 'Daniel Ferreira',
    email: 'daniel.ferreira@example.com',
    role: 'Senior Data Engineer',
    currentCompany: 'Atlas Fintech',
    location: 'Lisbon',
    status: 'INTERVIEW',
    expectedSalary: 145000,
    noticePeriodDays: 30,
    owner: 'Thomas Müller',
    notes: null,
    createdAt: '2026-05-22T09:00:00Z',
    updatedAt: '2026-07-06T15:10:00Z',
  },
  {
    id: 'cand_11',
    name: 'Grace Tan',
    email: 'grace.tan@example.com',
    role: 'Marketing Lead',
    currentCompany: 'Verdant Retail',
    location: 'Singapore',
    status: 'SCREENING',
    expectedSalary: 105000,
    noticePeriodDays: 30,
    owner: 'Kenji Watanabe',
    notes: null,
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-07-03T10:00:00Z',
  },
  {
    id: 'cand_12',
    name: 'Omar Haddad',
    email: 'omar.haddad@example.com',
    role: 'Full Stack Engineer',
    currentCompany: 'Meridian Payments',
    location: 'Dubai',
    status: 'OFFER',
    expectedSalary: 135000,
    noticePeriodDays: 30,
    owner: 'Leila Haddad',
    notes: 'Offer sent, awaiting acceptance.',
    createdAt: '2026-05-05T09:00:00Z',
    updatedAt: '2026-07-08T09:40:00Z',
  },
  {
    id: 'cand_13',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@example.com',
    role: 'Mobile Engineer',
    currentCompany: 'Lumen Studio',
    location: 'Osaka',
    status: 'APPLIED',
    expectedSalary: 118000,
    noticePeriodDays: 45,
    owner: 'Yuki Sato',
    notes: null,
    createdAt: '2026-07-04T09:00:00Z',
    updatedAt: '2026-07-04T09:00:00Z',
  },
  {
    id: 'cand_14',
    name: 'Elena Petrova',
    email: 'elena.petrova@example.com',
    role: 'Finance Business Partner',
    currentCompany: 'Atlas Fintech',
    location: 'Singapore',
    status: 'HIRED',
    expectedSalary: 128000,
    noticePeriodDays: 60,
    owner: 'Priya Nair',
    notes: 'Placed at Verdant Retail.',
    createdAt: '2026-03-30T09:00:00Z',
    updatedAt: '2026-06-15T12:00:00Z',
  },
  {
    id: 'cand_15',
    name: 'Marcus Lee',
    email: 'marcus.lee@example.com',
    role: 'Security Engineer',
    currentCompany: 'Cobalt Analytics',
    location: 'Singapore',
    status: 'SCREENING',
    expectedSalary: 150000,
    noticePeriodDays: 30,
    owner: 'Grace Ofori',
    notes: null,
    createdAt: '2026-06-12T09:00:00Z',
    updatedAt: '2026-07-02T14:00:00Z',
  },
];
