import type { Company } from './schema';

// Fake Client DB stand-in. Company names are reused by the job-orders and
// candidates mocks so the entities cross-reference like the real data model.
export const mockCompanies: Company[] = [
  {
    id: 'co_01',
    name: 'Meridian Payments',
    industry: 'Fintech',
    location: 'Singapore',
    relationshipStatus: 'TRADED',
    tobStatus: 'SIGNED',
    stakeholderCount: 4,
    openJobOrders: 3,
    owner: 'Daniel Wong',
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
  },
  {
    id: 'co_02',
    name: 'Northwind Logistics',
    industry: 'Supply Chain',
    location: 'Kuala Lumpur',
    relationshipStatus: 'WARM',
    tobStatus: 'SENT',
    stakeholderCount: 3,
    openJobOrders: 2,
    owner: 'Sofia Reyes',
    createdAt: '2024-05-03T09:00:00Z',
    updatedAt: '2026-07-05T09:00:00Z',
  },
  {
    id: 'co_03',
    name: 'Cobalt Analytics',
    industry: 'Data & AI',
    location: 'Singapore',
    relationshipStatus: 'TRADED',
    tobStatus: 'SIGNED',
    stakeholderCount: 5,
    openJobOrders: 4,
    owner: 'Leila Haddad',
    createdAt: '2023-11-20T09:00:00Z',
    updatedAt: '2026-07-08T09:00:00Z',
  },
  {
    id: 'co_04',
    name: 'Lumen Studio',
    industry: 'Design & Media',
    location: 'Singapore',
    relationshipStatus: 'WARM',
    tobStatus: 'SIGNED',
    stakeholderCount: 2,
    openJobOrders: 1,
    owner: 'Hannah Kim',
    createdAt: '2024-08-14T09:00:00Z',
    updatedAt: '2026-07-04T09:00:00Z',
  },
  {
    id: 'co_05',
    name: 'Atlas Fintech',
    industry: 'Fintech',
    location: 'Singapore',
    relationshipStatus: 'TRADED',
    tobStatus: 'SIGNED',
    stakeholderCount: 6,
    openJobOrders: 3,
    owner: 'Marcus Tan',
    createdAt: '2023-09-01T09:00:00Z',
    updatedAt: '2026-07-07T09:00:00Z',
  },
  {
    id: 'co_06',
    name: 'Verdant Retail',
    industry: 'Retail',
    location: 'Jakarta',
    relationshipStatus: 'WARM',
    tobStatus: 'SENT',
    stakeholderCount: 3,
    openJobOrders: 2,
    owner: 'Kenji Watanabe',
    createdAt: '2024-06-22T09:00:00Z',
    updatedAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'co_07',
    name: 'Harbor Health',
    industry: 'Healthcare',
    location: 'Singapore',
    relationshipStatus: 'COLD',
    tobStatus: 'NONE',
    stakeholderCount: 1,
    openJobOrders: 0,
    owner: 'Isabella Rossi',
    createdAt: '2026-06-30T09:00:00Z',
    updatedAt: '2026-06-30T09:00:00Z',
  },
  {
    id: 'co_08',
    name: 'Solaris Energy',
    industry: 'Energy',
    location: 'Bangkok',
    relationshipStatus: 'WARM',
    tobStatus: 'SENT',
    stakeholderCount: 2,
    openJobOrders: 1,
    owner: 'Thomas Müller',
    createdAt: '2024-10-11T09:00:00Z',
    updatedAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'co_09',
    name: 'Keystone Property',
    industry: 'Real Estate',
    location: 'Hong Kong',
    relationshipStatus: 'UNS',
    tobStatus: 'NONE',
    stakeholderCount: 1,
    openJobOrders: 0,
    owner: 'Grace Ofori',
    createdAt: '2025-01-18T09:00:00Z',
    updatedAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'co_10',
    name: 'Pinnacle Consulting',
    industry: 'Professional Services',
    location: 'Singapore',
    relationshipStatus: 'TRADED',
    tobStatus: 'SIGNED',
    stakeholderCount: 4,
    openJobOrders: 2,
    owner: 'Priya Nair',
    createdAt: '2023-12-05T09:00:00Z',
    updatedAt: '2026-07-02T09:00:00Z',
  },
  {
    id: 'co_11',
    name: 'Orchid Biotech',
    industry: 'Biotech',
    location: 'Singapore',
    relationshipStatus: 'COLD',
    tobStatus: 'NONE',
    stakeholderCount: 1,
    openJobOrders: 0,
    owner: 'Yuki Sato',
    createdAt: '2026-06-20T09:00:00Z',
    updatedAt: '2026-06-20T09:00:00Z',
  },
  {
    id: 'co_12',
    name: 'Ironclad Security',
    industry: 'Cybersecurity',
    location: 'Sydney',
    relationshipStatus: 'WARM',
    tobStatus: 'SENT',
    stakeholderCount: 2,
    openJobOrders: 1,
    owner: 'Grace Ofori',
    createdAt: '2024-09-27T09:00:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
  },
];
