import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { LocationLevel, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { CreateLocationDto } from './dto/create-location.dto';
import { QueryLocationsDto } from './dto/query-locations.dto';

/** Which rung each level must sit under. COUNTRY is the root and has no parent. */
const PARENT_LEVEL: Record<LocationLevel, LocationLevel | null> = {
  COUNTRY: null,
  STATE: 'COUNTRY',
  CITY: 'STATE',
  SUBURB: 'CITY',
};

@Injectable()
export class LocationsService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Search/browse the tree. Every read is capped: the tree is ~2k nodes today
   * and grows with each dump loaded, so nothing here returns "all locations".
   *
   * The two hierarchy filters answer different questions and both earn their
   * keep — `parentId` is one step down (a cascading picker listing a country's
   * states), `underId` is the whole subtree at any depth (resolved through the
   * denormalized ancestor path, so one country id matches all 1,500 nodes
   * beneath it without a recursive query).
   */
  findAll(query: QueryLocationsDto) {
    const where: Prisma.LocationWhereInput = {};

    if (query.q) {
      where.name = { contains: query.q, mode: Prisma.QueryMode.insensitive };
    }
    if (query.level) {
      where.level = query.level;
    }
    if (query.parentId) {
      where.parentId = query.parentId;
    }
    if (query.underId) {
      where.ancestorIds = { has: query.underId };
    }

    // Level before name so a mixed-level result reads top-down (countries,
    // then states, then cities) instead of interleaving rungs alphabetically.
    return this.prisma.location.findMany({
      where,
      orderBy: [{ level: 'asc' }, { name: 'asc' }],
      take: query.take,
    });
  }

  async findOne(id: string) {
    const location = await this.prisma.location.findUnique({ where: { id } });
    if (!location) {
      throw new NotFoundException(`Location ${id} not found`);
    }
    return location;
  }

  /**
   * Admin-only (see the controller). Maintains `ancestorIds` itself — the
   * column the scope resolver reads — because a node written without it would
   * be invisible to every location grant, silently.
   */
  async create(dto: CreateLocationDto) {
    const expectedParentLevel = PARENT_LEVEL[dto.level];

    if (expectedParentLevel === null) {
      if (dto.parentId) {
        throw new BadRequestException({
          code: 'INVALID_PARENT',
          message: 'A COUNTRY sits at the root and cannot have a parent.',
        });
      }
    } else if (!dto.parentId) {
      throw new BadRequestException({
        code: 'PARENT_REQUIRED',
        message: `A ${dto.level} must sit under a ${expectedParentLevel}.`,
      });
    }

    let ancestorIds: string[] = [];
    if (dto.parentId) {
      const parent = await this.prisma.location.findUnique({
        where: { id: dto.parentId },
        select: { id: true, level: true, ancestorIds: true },
      });
      if (!parent) {
        throw new BadRequestException({
          code: 'INVALID_PARENT',
          message: `Unknown parent location ${dto.parentId}.`,
        });
      }
      // The tree's rungs are fixed, so a CITY under a COUNTRY is a data bug,
      // not a shortcut — it would break the ancestor walk both ways.
      if (parent.level !== expectedParentLevel) {
        throw new BadRequestException({
          code: 'INVALID_PARENT_LEVEL',
          message: `A ${dto.level} must sit under a ${expectedParentLevel}, but ${dto.parentId} is a ${parent.level}.`,
        });
      }
      ancestorIds = parent.ancestorIds;
    }

    if (dto.postcode && dto.level !== 'SUBURB') {
      throw new BadRequestException({
        code: 'POSTCODE_NOT_ALLOWED',
        message: 'postcode is only meaningful at SUBURB level.',
      });
    }

    // Two steps, because ancestorIds includes the row's own id and cuid()
    // is generated by the insert — there's no id to embed until it exists.
    const created = await this.prisma.location.create({
      data: {
        name: dto.name.trim(),
        level: dto.level,
        parentId: dto.parentId ?? null,
        postcode: dto.postcode ?? null,
        geonameId: dto.geonameId ?? null,
        ancestorIds: [],
      },
    });
    return this.prisma.location.update({
      where: { id: created.id },
      data: { ancestorIds: [created.id, ...ancestorIds] },
    });
  }
}
